### ISSUE TITLE
Exception when changing the shutter speed slider value

### ISSUE THREAD

**Issue by Passiday** [alexd3rsan/rollingshutterpy#1]
It is not possible to change the shutter speed slider value, I get this exception:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "./rollingshutter.py", line 160, in update_speed
    self.label_speed.config(text='Shutter Speed: '+str(self.tk_speed_val.get()))
  File "/usr/lib/python3.5/tkinter/__init__.py", line 358, in get
    return self._tk.getint(self._tk.globalgetvar(self._name))
TypeError: getint() argument must be str, not float
```
Also, it might be beneficial to allow shutter speed value between 0 and 1 - if the changes in frames are too quick, you might want to pick a batch of lines from each frame.

**Comment by alexd3rsan** [comment]
What exactly did you change about about the slider value? Are we talking backend or actual run-time?

Thanks for your report(s) and your time!

**Comment by Passiday** [comment]
I am not changing anything in the code. I just launch the program from command line, select the input and output, then try to change the slider. The exception immediately is thrown. Might be a tkinter version thing, I don't know. I have version 8.6.
